In [191]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [192]:
df = pd.read_excel('D://Internship//dataset//COVID-19.xlsx')
df[:5]

Sno  age  gender  body temperature  Dry Cough  sour throat  weakness  \
0    1   20       1              98.6          0            0         0   
1    2   19       1              99.0          1            0         0   
2    3   55       0             102.0          1            1         1   
3    4   40       0             100.0          0            0         0   
4    5   33       1              99.2          0            1         0   

   breathing problem  drowsiness  pain in chest  ...  diabetes  heart disease  \
0                  0           0              0  ...         0              0   
1                  0           0              0  ...         0              0   
2                  1           1              1  ...         0              0   
3                  0           1              1  ...         1              0   
4                  1           0              0  ...         0              0   

   lung disease  stroke or reduced immunity  symptoms progressed  \
0             0                           0                    0   
1             0                           0                    0   
2             0                           0                    0   
3             0                           0                    1   
4             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Corona result  
0                       0              0  
1                       0              0  
2                       0              1  
3                       0              2  
4                       1              2  

[5 rows x 21 columns]

In [193]:
df.shape

(127, 21)

In [194]:
labels = np.array(df['Corona result'])
labels[:5]

array([0, 0, 1, 2, 2], dtype=int64)

In [195]:
feature = df.drop(['Corona result','Sno', 'stroke or reduced immunity','Loss of sense of smell',
                   'diabetes', 'heart disease', 'kidney disease','lung disease'], axis=1)
# print(feature.describe())
feature[:5]

age  gender  body temperature  Dry Cough  sour throat  weakness  \
0   20       1              98.6          0            0         0   
1   19       1              99.0          1            0         0   
2   55       0             102.0          1            1         1   
3   40       0             100.0          0            0         0   
4   33       1              99.2          0            1         0   

   breathing problem  drowsiness  pain in chest  \
0                  0           0              0   
1                  0           0              0   
2                  1           1              1   
3                  0           1              1   
4                  1           0              0   

   travel history to infected countries  symptoms progressed  \
0                                     0                    0   
1                                     0                    0   
2                                     0                    0   
3                                     1                    1   
4                                     1                    1   

   high blood pressue  change in appetide  
0                   0                   0  
1                   0                   0  
2                   0                   1  
3                   1                   1  
4                   0                   0

In [196]:
feature = np.array(feature)
feature.shape

(127, 13)

In [197]:
rf = KNeighborsClassifier(n_neighbors=3,p=1)

In [198]:
X_train, X_test, y_train, y_test = train_test_split(feature, labels, test_size=0.2, random_state=30)

In [199]:
print("Training data Size: ", X_train.shape)
print("Test data Sie: ", X_test.shape)

Training data Size:  (101, 13)
Test data Sie:  (26, 13)


In [200]:
rf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=1,
                     weights='uniform')

In [201]:
prediction = rf.predict(X_test)
prediction[:10]

array([0, 0, 0, 2, 0, 1, 1, 0, 1, 1], dtype=int64)

In [202]:
print("Actual Value:    ", y_test)
print("Predicted Value: ", prediction)

Actual Value:     [0 0 1 1 2 0 1 0 1 0 2 1 0 1 1 1 0 2 1 0 1 1 1 1 1 0]
Predicted Value:  [0 0 0 2 0 1 1 0 1 1 1 1 0 1 1 1 0 2 0 1 1 2 1 1 1 0]


In [203]:
acc = accuracy_score(prediction, y_test)
acc

0.6538461538461539

In [209]:
pred = rf.predict([[15,1,102.0,0,1,1,1,1,1,0,1,0,1]])
pred * 100

array([100], dtype=int64)

In [220]:
pred = rf.predict_proba([[15,0,102.1,1,1,1,1,1,1,0,1,0,1]])
predic = pred[0][1]+pred[0][2]
predic

1.0

In [219]:
import pickle
file = open('knn148.pkl','wb')
pickle.dump(rf, file)
file.close()