In [65]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [66]:
df = pd.read_csv('dataset/made.csv')
df

age  runny_nose  diff_breath   fever  sore_throat  cough  pain  \
0      28          15           20   99.00           18     16    19   
1      49          17           18  102.00           11     10    18   
2      44          13           11  101.17           20      4     3   
3      52           2           16   98.63           17      3    19   
4      20          13            2   98.37           15     19     8   
5      20           7            2   99.32            6     11     9   
6      32           3            9  101.67           20     17    14   
7      53          16           12   99.38            2     10     4   
8      54          10           20   98.72           10     12    16   
9      61           6            9  103.79           19     13    12   
10     58          19            4  100.92           10      7    12   
11     66           3            6  101.89           18      9     6   
12     21          15            9   96.18           20      7    15   
13     12          16           14   98.54           18     20    13   
14     29           2            2  103.56            7      9     2   
15     55           5           12   98.14            6     11    12   
16     59           7           20  101.53           12     20     3   
17     61           7           18  100.39            4     14    18   
18     69           1           18   99.24           11      9    19   
19     40          18            9  102.33            6     10     1   
20     35          12           13  101.02            1     16     3   
21     17          19            6   97.03           19      1    20   
22     53           6           16   96.09           17      1    18   
23     13          16           12  102.44           14     16    15   
24     65           7           11  103.30           19     17     6   
25     54          18           10   96.94            7     16    11   
26     46           9            3   98.16           12     20     7   
27     48          20            4   99.65           18      7    20   
28     22          11           13   99.72           18     10    15   
29     55          13            7  101.84           18      7    16   
...   ...         ...          ...     ...          ...    ...   ...   
1348   42          18           16  102.46           15     16    10   
1349   31          14            9   98.77           10     11     8   
1350   42           5           16   97.57           20      6     2   
1351   37          18            2   97.69            3     17    14   
1352   14          18           17  102.81           16     10    17   
1353   23          14           19   96.01           13      6     9   
1354   61          20            4   96.11           14      1     3   
1355   68           4            6   98.00            3     11     9   
1356   16           5            7  102.47           18      8     5   
1357   59           1           17  103.40           18     15     9   
1358   53           7            2   96.23           17     17     4   
1359   23          17           16  100.16            7     13     8   
1360   29           6           18  102.34           16     16    14   
1361   68          20           12   96.23           13     15    10   
1362   31           1           17  103.21           11     16    12   
1363   67          17            8   97.19           13     15    18   
1364    8           5           12  102.51           14      1    10   
1365   36          18            2  101.18            8     13    18   
1366   14           5           10   98.37           13     17    16   
1367   21          19            3  103.84           13      2     7   
1368    8           5           18  103.33            6     20     5   
1369   27           7           13   98.99           20     20    20   
1370   22           7           20   99.99           17     18    16   
1371   68           4            8  102.78    

In [67]:
df.shape

(1378, 10)

In [68]:
df.describe()

age   runny_nose  diff_breath        fever  sore_throat  \
count  1378.000000  1378.000000  1378.000000  1378.000000  1378.000000   
mean     37.634978    10.356313    10.417997    99.949833    10.602322   
std      19.324981     5.911478     5.661297     2.319747     5.803742   
min       5.000000     1.000000     1.000000    96.010000     1.000000   
25%      21.000000     5.000000     6.000000    97.940000     6.000000   
50%      37.000000    10.000000    10.000000   100.020000    11.000000   
75%      55.000000    16.000000    15.000000   101.955000    16.000000   
max      70.000000    20.000000    20.000000   103.990000    20.000000   

             cough         pain     diarrhea       gender     infected  
count  1378.000000  1378.000000  1378.000000  1378.000000  1378.000000  
mean     10.455007    10.380261    10.600145     0.486938     0.494194  
std       5.710882     5.845800     5.720726     0.500011     0.500148  
min       1.000000     1.000000     1.000000     0.000000     0.000000  
25%       6.000000     5.000000     6.000000     0.000000     0.000000  
50%      11.000000    10.000000    11.000000     0.000000     0.000000  
75%      15.000000    16.000000    15.750000     1.000000     1.000000  
max      20.000000    20.000000    20.000000     1.000000     1.000000

In [69]:
labels = np.array(df['infected'])
labels[:5]

array([1, 1, 1, 1, 0], dtype=int64)

In [99]:
feature = df.drop(['infected','age'], axis=1)
# feature = df.drop('age', axis=1)
print(feature[:10])
feature = np.array(feature)
feature[:5]

   runny_nose  diff_breath   fever  sore_throat  cough  pain  diarrhea  gender
0          15           20   99.00           18     16    19        14       0
1          17           18  102.00           11     10    18        17       1
2          13           11  101.17           20      4     3        10       0
3           2           16   98.63           17      3    19         9       0
4          13            2   98.37           15     19     8        14       1
5           7            2   99.32            6     11     9         1       1
6           3            9  101.67           20     17    14         8       0
7          16           12   99.38            2     10     4        16       0
8          10           20   98.72           10     12    16         7       1
9           6            9  103.79           19     13    12         6       1


array([[ 15.  ,  20.  ,  99.  ,  18.  ,  16.  ,  19.  ,  14.  ,   0.  ],
       [ 17.  ,  18.  , 102.  ,  11.  ,  10.  ,  18.  ,  17.  ,   1.  ],
       [ 13.  ,  11.  , 101.17,  20.  ,   4.  ,   3.  ,  10.  ,   0.  ],
       [  2.  ,  16.  ,  98.63,  17.  ,   3.  ,  19.  ,   9.  ,   0.  ],
       [ 13.  ,   2.  ,  98.37,  15.  ,  19.  ,   8.  ,  14.  ,   1.  ]])

In [85]:
rf = RandomForestRegressor(n_estimators= 100, random_state = 42)

In [86]:
X_train, X_test, y_train, y_test = train_test_split(feature, labels, test_size=0.2, random_state=10)

In [87]:
print("Training data Size: ", X_train.shape)
print("Test data Sie: ", X_test.shape)

Training data Size:  (1102, 8)
Test data Sie:  (276, 8)


In [88]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [92]:
prediction = rf.predict(X_test)
prediction[:10]

array([0.51, 0.58, 0.55, 0.5 , 0.51, 0.48, 0.43, 0.43, 0.57, 0.39])

In [90]:
print("Actual Value: ", y_test[:5])
print("Predicted Value: ", prediction[:5])

Actual Value:  [0 1 1 1 1]
Predicted Value:  [0.51 0.58 0.55 0.5  0.51]


In [98]:
predictions = rf.predict([[18,20,99.3,18,1,15,20,1]])
predictions * 100

array([54.])